[package]
name = "rho_q_asarray"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rho_q_asarray"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.21.0"
numpy = "0.21"
num-complex = "0.4"
